name: Update FreeFileSync Cask

on:
  schedule:
    - cron: '0 6 1 * *'  # Monthly
  workflow_dispatch:

jobs:
  update-cask:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get latest version
        id: version
        run: |
          VERSION=$(curl -s https://freefilesync.org/download.php | grep -oE 'FreeFileSync [0-9.]+' | head -n1 | awk '{print $2}' | sed 's/\.$//')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if update is needed
        id: check
        run: |
          CURRENT=$(grep -oE 'version "[^"]+"' Casks/freefilesync.rb | cut -d'"' -f2)
          echo "Current: $CURRENT, Latest: ${{ steps.version.outputs.version }}"
          if [ "$CURRENT" = "${{ steps.version.outputs.version }}" ]; then
            echo "No update needed"
            echo "update_needed=false" >> $GITHUB_OUTPUT
          else
            echo "Update needed"
            echo "update_needed=true" >> $GITHUB_OUTPUT

      - name: Download zip and calculate sha256
        if: steps.check.outputs.update_needed == 'true'
        id: sha
        run: |
          curl -Lo ffs.zip "https://freefilesync.org/download/FreeFileSync_${{ steps.version.outputs.version }}_macOS.zip"
          SHA=$(shasum -a 256 ffs.zip | awk '{print $1}')
          echo "sha256=$SHA" >> $GITHUB_OUTPUT

      - name: Update Cask file
        if: steps.check.outputs.update_needed == 'true'
        run: |
          sed -i '' "s/^  version \".*\"/  version \"${{ steps.version.outputs.version }}\"/" Casks/freefilesync.rb
          sed -i '' "s/^  sha256 \".*\"/  sha256 \"${{ steps.sha.outputs.sha256 }}\"/" Casks/freefilesync.rb

      - name: Commit and push
        if: steps.check.outputs.update_needed == 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git commit -am "Update FreeFileSync to v${{ steps.version.outputs.version }}"
          git push